### PR TITLE
docs: Add references for content translation

### PR DESCRIPTION
**Pull request by founderblocks-sils**
I've been trying to find that info for quite a while, maybe this'll help others find it faster.

### CODE REVIEW

**Comment by RCheesley** [comment]
Hi @founderblocks-sils and thanks for adding this! Unfortunately as mentioned [in the readme](https://github.com/mautic/mautic-documentation#mautic-documentation), we're not accepting PRs on this repository any more because we're about to launch the new docs over at https://github.com/mautic/user-documentation - would you mind adding the content there? Happy to help re. how to link to other sections in the docs using the new RST syntax if you need any help - just ping in the #t-education channel on Slack (https://mautic.org/slack for an invite) Thanks in advance!

**Comment by founderblocks-sils** [comment]
hey, no time today but understood, I just clicked "edit on github" on the docs and wanted to give you a quick patch and that led me to this file. In case you get a lot of PRs like these, you might want to fix the edit on github links on the latest documentation to lead to the new location directly.

Currently focusing on some other things so I'm unlikely going to be able to take the time soon to port this over. Next time.

**Comment by RCheesley** [comment]
Yeah, we're going to be launching imminently (with Mautic 5) and it's not possible to easily switch up that link unfortunately as it's dynamically created based on the file location within Grav. I'll see if one of the team can pull it over!

**Comment by RCheesley** [comment]
@mautic/education-team pinging for this to come over to the new docs! cc @RCheesley to get into my todo list too! 😊

**Pull request closed without merging**
