### PR TITLE
Add contact ID

### LINKED ISSUE #111: ContactId customfield {id} is not in docs
There is not any evidence in docs, that custom filed {id}, like {contactfield=id}, can be used as well.

Please add it to all necessary places like https://docs.mautic.org/en/setup/variables and so on..

### PR DESCRIPTION
**Pull request by tompon**
Add missing Contact ID fixes #111

### CODE REVIEW

**Review by RCheesley — CHANGES_REQUESTED** [review]
Fab! Thanks for making this change - I forgot to mention that it also needs to be added to the alphabetical list at the bottom of the page!

If you can go to 'files changed' at the top of this PR and then edit the file to add the same line in the correct place, we can get this merged!

(p.s. I did not know about this token so thanks ... learn something new every day!)

**Comment by tompon** [comment]
Done, thank you Ruth

**Review by RCheesley — APPROVED** [review]
Awesome, let's get it merged! 🚀

**Comment by escopecz** [comment]
@tompon welcome to Mautic contributors! Great work!

**Pull request merged**
