### PR TITLE
Alter Queue Configuration docs for  #9391

### LINKED ISSUE #152: Update documentation on queues
Since 3.x users who are implementing RabbitMQ or Beanstalkd need to configure the settings directly in the local configuration file - we removed the GUI interface with this [commit](https://github.com/mautic/mautic/commit/74b8c3e942636a953b081a285c5b696563806662#diff-0c8e7cb890a2152fe377180fde4a86b3314a41f4933622578bfd53b599f26f29).

We need to update the docs relating to the queue to reflect this and include the required syntax/configuration as an example.

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/95780476-update-documentation-on-queues?utm_campaign=plugin&utm_content=tracker%2F178811078&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F178811078&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by maxlawton**
Replaced GUI-based configuration docs for RabbitMQ with a table describing configuration parameters to be managed via `local.php`.

Added two parameters introduced in https://github.com/mautic/mautic/pull/9391.

Fixes #152

### CODE REVIEW

**Comment by RCheesley** [comment]
@maxlawton thanks for making the PR! We had an open issue in #152 for this, but I wonder if we would need to include beanstalkd or would the params be the same regardless of platform?

Also @fakela you had asked to be assigned #152 but I think that work has not yet started so I will remove that assignment.

**Comment by maxlawton** [comment]
@RCheesley I haven't used beanstalkd personally. The configuration parameters are different and fewer for that service:

| Parameter            | Default       | Description                                         |
|----------------------|---------------|-----------------------------------------------------|
| *beanstalkd_host*    | `'localhost'` | The hostname of the Beanstalkd server               |
| *beanstalkd_port*    | `'11300'`     | The port that the Beanstalkd server is listening on |
| *beanstalkd_timeout* | `'60'`        | The default TTR for Beanstalkd jobs                 |

Would you like me to replace the beanstalkd configuration docs with the table above in this PR? That info was simply copied from here: https://github.com/mautic/mautic/blob/features/app/bundles/QueueBundle/Config/config.php#L57-L62

**Comment by fakela** [comment]
> @maxlawton thanks for making the PR! We had an open issue in #152 for this, but I wonder if we would need to include beanstalkd or would the params be the same regardless of platform?
> 
> Also @fakela you had asked to be assigned #152 but I think that work has not yet started so I will remove that assignment.

Thanks @maxlawton for working on this, I haven't really have the time to work on this

**Comment by maxlawton** [comment]
@RCheesley, @fakela I should point out that this PR includes configuration parameters that will not exist until https://github.com/mautic/mautic/pull/9391 is released. If you'd like the queue documentation updated ASAP, I can submit a rebase of this PR, omitting my second commit which pertains to the new params (and add beanstalkd info if desired).

**Comment by fakela** [comment]
> @RCheesley, @fakela I should point out that this PR includes configuration parameters that will not exist until [mautic/mautic#9391](https://github.com/mautic/mautic/pull/9391) is released. If you'd like the queue documentation updated ASAP, I can submit a rebase of this PR, omitting my second commit which pertains to the new params (and add beanstalkd info if desired).

@maxlawton I don't know when this [mautic/mautic#9391](https://github.com/mautic/mautic/pull/9391 will be released but I feel we still need the information there as it will be important in the future, maybe you could leave the PR the way it is and add the Beanstalk info

**Comment by fakela** [comment]
Thanks for this @maxlawton. @RCheesley please review

**Comment by RCheesley** [comment]
Great thanks for this @maxlawton - as we have your PR slated for 4.0 beta at the end of this month we should not have too much of a wait to get it into a release.  Just need to get folk to test and code review the PR :) 

Thanks for making the updates!

**Comment by RCheesley** [comment]
@maxlawton please can you pull in the changes from the master branch - as this is on a protected repo we can't do it as maintainers.

**Comment by RCheesley** [comment]
@maxlawton need to pull in the master branch here too please and thank you! 🙇‍♀️

**Comment by RCheesley** [comment]
@all-contributors please add @maxlawton for docs

**Comment by RCheesley** [comment]
@all-contributors please add @maxlawton for docs

**Pull request merged**
